### ISSUE TITLE
Programmatically add output directory as source root

### ISSUE THREAD

**Issue by willhains** [bohnman/package-info-maven-plugin#6]
Would be nice to not have to explicitly add the generated code as a source root.
According to [this StackOverflow answer][so], the plugin can do this programmatically.

[so]: https://stackoverflow.com/a/30760908/554518

**Comment by willhains** [comment]
@bohnman I have submitted a PR (#8) that implements this feature. Could you consider releasing a new version that includes it?

**Comment by bohnman** [comment]
Hi Will.  Unfortunately, the demands of my personal and professional life don’t allow for time to maintain open source projects.  Please feel free to fork this project.  Best wishes!

**Comment by willhains** [comment]
@bohnman That's understandable. OK, I will try to publish this under my own groupId. I will reply again here if/when it is available on Central. Thanks again for making a very useful plugin! :)

**Comment by willhains** [comment]
@bohnman I published [my fork](https://github.com/willhains/package-info-maven-plugin) with #8 and #9 as [io.github.willhains:package-info-maven-plugin:1.2.0](https://search.maven.org/artifact/io.github.willhains/package-info-maven-plugin/1.2.0/maven-plugin).
